spring.application.name=demo
spring.mvc.problemdetails.enabled=true
springdoc.override-with-generic-response=false
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}
server.servlet.context-path=/demo/api/

# Database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.open-in-view=false

spring.jpa.database=postgresql
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://ep-bold-mode-ad1849i5-pooler.c-2.us-east-1.aws.neon.tech/neondb}
spring.datasource.username=${POSTGRES_USER:neondb_owner}
spring.datasource.password=${POSTGRES_PASS:npg_Xw1s0hrDEONZ}
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always

# Configuração do Cross Origin Request Site (CORS)
app.cors.allow-credentials=${APP_CORS_ALLOW_CREDENTIALS:false}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:*}
app.cors.allowed-methods=${APP_CORS_ALLOWED_METHODS:*}
app.cors.allowed-headers=${APP_CORS_ALLOWED_HEADERS:*}
