package br.edu.ifpb.es.daw.todo.model.enums;

public enum GinasioNome {
    FORTALEZA_NUCLEO_ROCHOSO, SANTUARIO_MARES_AZUIS, BASE_CHOQUE_RELAMPAGO, JARDIM_ESMERALDA_SILENCIOSO, DOJO_SOMBRAS_TOXICAS, TEMPLO_MENTE_SUPREMA, FORJA_VULCANICA_ARDENTE, TRONO_DOMINIO_TERRESTRE

}
