package br.edu.ifpb.es.daw.todo.model.enums;

public enum Locais {
    ROUTE, CITY, FOREST, CAVE, MOUNTAIN, BEACH, OCEAN, RIVER, LAKE, DESERT, SWAMP, VOLCANO, RUINS, TOWER, LABORATORY, POWER_PLANT, FACTORY, DOJO, GYM, STADIUM, ARENA, ELITE_FOUR_ROOM, CHAMPION_ROOM, SAFARI_ZONE, VICTORY_ROAD, POKEMON_LEAGUE, BATTLE_TOWER, BATTLE_FRONTIER, SPACE, DISTORTION_WORLD

}
